### PR TITLE
Stabilize scope

### PR DESCRIPTION
**Pull request by nikomatsakis**
I think the `scope()` API has proven its worth by now, so let's remove it from the "unstable" feature. I did make one tweak to the API: the `scope()` closure can now return a result.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@cuviper any objections? otherwise, I'm inclined to merge.

**Comment by cuviper** [comment]
Let's do it!

**Comment by cuviper** [comment]
Hmm, my merge commit [stalled in Travis](https://travis-ci.org/nikomatsakis/rayon/jobs/188270401#L660) on `thread_pool::test::workers_stop`.

**Comment by nikomatsakis** [comment]
@cuviper interesting. not related to this PR, i'm sure, but perhaps a latent bug ?

**Pull request merged**
