### PR TITLE
Port from deque to crossbeam

### PR DESCRIPTION
**Pull request by cuviper**
This is presented for consideration of #33.

### CODE REVIEW

**Comment by cuviper** [comment]
Here's `cargo benchcmp`:

```
 name                                                     bench-master ns/iter  bench-crossbeam ns/iter  diff ns/iter   diff %
 factorial::factorial_iterator                            26,908,930            26,930,608                     21,678    0.08%
 factorial::factorial_join                                9,200,819             9,510,002                     309,183    3.36%
 factorial::factorial_par_iter                            9,585,641             9,598,103                      12,462    0.13%
 factorial::factorial_recursion                           11,660,189            11,730,915                     70,726    0.61%
 fibonacci::fibonacci_iterative                           6                     6                                   0    0.00%
 fibonacci::fibonacci_join_1_2                            53,646,171            76,934,376                 23,288,205   43.41%
 fibonacci::fibonacci_join_2_1                            53,846,499            87,536,713                 33,690,214   62.57%
 fibonacci::fibonacci_recursive                           12,659,770            12,134,829                   -524,941   -4.15%
 find::size1::parallel_find_common                        6,905                 7,955                           1,050   15.21%
 find::size1::parallel_find_first                         5,150                 5,594                             444    8.62%
 find::size1::parallel_find_last                          2,862,121             2,875,659                      13,538    0.47%
 find::size1::parallel_find_middle                        1,763,111             1,846,432                      83,321    4.73%
 find::size1::parallel_find_missing                       3,125,191             3,136,468                      11,277    0.36%
 find::size1::serial_find_common                          4,632                 4,879                             247    5.33%
 find::size1::serial_find_first                           1                     1                                   0    0.00%
 find::size1::serial_find_last                            6,169,895             6,186,982                      17,087    0.28%
 find::size1::serial_find_middle                          4,116,349             4,120,126                       3,777    0.09%
 find::size1::serial_find_missing                         6,178,036             6,172,536                      -5,500   -0.09%
 join_microbench::increment_all                           43,598                54,530                         10,932   25.07%
 join_microbench::join_recursively                        913,413               1,598,844                     685,431   75.04%
 map_collect::i_mod_10_to_i::with_collect                 8,144,274             8,293,455                     149,181    1.83%
 map_collect::i_mod_10_to_i::with_fold                    1,733,508             1,757,988                      24,480    1.41%
 map_collect::i_mod_10_to_i::with_fold_vec                1,947,785             1,975,713                      27,928    1.43%
 map_collect::i_mod_10_to_i::with_linked_list             16,133,705            16,293,877                    160,172    0.99%
 map_collect::i_mod_10_to_i::with_linked_list_vec         6,855,991             7,172,135                     316,144    4.61%
 map_collect::i_mod_10_to_i::with_linked_list_vec_sized   8,156,820             8,273,131                     116,311    1.43%
 map_collect::i_mod_10_to_i::with_mutex                   67,417,440            68,472,989                  1,055,549    1.57%
 map_collect::i_mod_10_to_i::with_mutex_vec               9,026,149             9,125,809                      99,660    1.10%
 map_collect::i_to_i::with_collect                        17,371,213            17,228,411                   -142,802   -0.82%
 map_collect::i_to_i::with_fold                           60,156,689            59,310,750                   -845,939   -1.41%
 map_collect::i_to_i::with_fold_vec                       60,025,973            59,557,241                   -468,732   -0.78%
 map_collect::i_to_i::with_linked_list                    32,184,883            32,060,744                   -124,139   -0.39%
 map_collect::i_to_i::with_linked_list_vec                40,505,721            40,798,240                    292,519    0.72%
 map_collect::i_to_i::with_linked_list_vec_sized          19,179,810            19,163,719                    -16,091   -0.08%
 map_collect::i_to_i::with_mutex                          107,357,058           109,152,158                 1,795,100    1.67%
 map_collect::i_to_i::with_mutex_vec                      64,699,257            64,459,804                   -239,453   -0.37%
 matmul::bench::bench_matmul_strassen                     4,902,295             5,135,220                     232,925    4.75%
 mergesort::bench::merge_sort_par_bench                   6,438,810             6,379,782                     -59,028   -0.92%
 mergesort::bench::merge_sort_seq_bench                   35,892,610            31,087,184                 -4,805,426  -13.39%
 nbody::bench::nbody_par                                  16,017,784            16,038,679                     20,895    0.13%
 nbody::bench::nbody_parreduce                            21,382,296            23,380,523                  1,998,227    9.35%
 nbody::bench::nbody_seq                                  80,110,519            79,965,827                   -144,692   -0.18%
 pythagoras::euclid_faux_serial                           32,327,901            32,309,458                    -18,443   -0.06%
 pythagoras::euclid_parallel_full                         45,152,968            65,752,503                 20,599,535   45.62%
 pythagoras::euclid_parallel_one                          32,329,917            32,437,711                    107,794    0.33%
 pythagoras::euclid_parallel_outer                        6,031,806             6,084,912                      53,106    0.88%
 pythagoras::euclid_parallel_weightless                   6,638,483             6,972,637                     334,154    5.03%
 pythagoras::euclid_serial                                32,293,770            32,783,297                    489,527    1.52%
 quicksort::bench::quick_sort_par_bench                   10,583,717            10,623,257                     39,540    0.37%
 quicksort::bench::quick_sort_seq_bench                   37,770,980            37,939,022                    168,042    0.44%
 sieve::bench::sieve_chunks                               9,470,565             9,470,761                         196    0.00%
 sieve::bench::sieve_parallel                             3,853,255             3,833,932                     -19,323   -0.50%
 sieve::bench::sieve_serial                               12,558,337            12,606,548                     48,211    0.38%
 tsp::bench::dj10                                         12,357,020            12,473,683                    116,663    0.94%
 vec_collect::vec_i::with_collect                         2,836,506             2,882,234                      45,728    1.61%
 vec_collect::vec_i::with_collect_into                    2,837,733             2,878,113                      40,380    1.42%
 vec_collect::vec_i::with_collect_into_reused             1,934,672             1,948,153                      13,481    0.70%
 vec_collect::vec_i::with_fold                            24,996,563            24,793,891                   -202,672   -0.81%
 vec_collect::vec_i::with_linked_list_vec                 12,973,525            13,080,659                    107,134    0.83%
 vec_collect::vec_i::with_linked_list_vec_sized           9,174,103             9,268,067                      93,964    1.02%
 vec_collect::vec_i_filtered::with_collect                9,169,056             9,231,937                      62,881    0.69%
 vec_collect::vec_i_filtered::with_fold                   25,490,712            25,080,885                   -409,827   -1.61%
 vec_collect::vec_i_filtered::with_linked_list_vec        13,182,650            13,118,740                    -63,910   -0.48%
 vec_collect::vec_i_filtered::with_linked_list_vec_sized  9,205,192             9,317,240                     112,048    1.22%
```

**Comment by cuviper** [comment]
My takeaway: no significant wins, and big losses in a few where the deques are probably highly contended: `join_microbench::*`, `fibonacci::fibonacci_join_*`, and `pythagoras::euclid_parallel_full`.

A perf report on `join_microbench` shows a lot of hotspots in crossbeam's `epoch` code.

```
Overhead  Command          Shared Object                      Symbol
  21.71%  rayon_demo-d0ef  rayon_demo-d0efdf21d5fa1508        [.] crossbeam::mem::epoch::participant::Participant::enter
  19.30%  rayon_demo-d0ef  rayon_demo-d0efdf21d5fa1508        [.] rayon::registry::WorkerThread::pop
  13.93%  rayon_demo-d0ef  rayon_demo-d0efdf21d5fa1508        [.] rayon::par_iter::internal::bridge_producer_consumer::helper
   8.72%  rayon_demo-d0ef  rayon_demo-d0efdf21d5fa1508        [.] rayon::registry::WorkerThread::push
   6.59%  rayon_demo-d0ef  rayon_demo-d0efdf21d5fa1508        [.] __rust_maybe_catch_panic
   5.98%  rayon_demo-d0ef  rayon_demo-d0efdf21d5fa1508        [.] crossbeam::mem::epoch::guard::pin
   4.83%  rayon_demo-d0ef  rayon_demo-d0efdf21d5fa1508        [.] <crossbeam::sync::chase_lev::Stealer<T>>::steal
   3.80%  rayon_demo-d0ef  rayon_demo-d0efdf21d5fa1508        [.] <crossbeam::mem::epoch::guard::Guard as core::ops::Drop>::drop
   3.19%  rayon_demo-d0ef  rayon_demo-d0efdf21d5fa1508        [.] rayon::registry::in_worker
   3.17%  rayon_demo-d0ef  rayon_demo-d0efdf21d5fa1508        [.] rayon::registry::in_worker
```

**Comment by nikomatsakis** [comment]
Charts. These basically back up your observations that it's usually slower, particularly on micro-benchmarks.

Medians, normalized to 100:

medians

All data points:

all points

**Comment by cuviper** [comment]
OK, do we agree to close this and #33?  Or should we ask the `crossbeam` authors to try and close the performance gap?  (especially since `deque` seems unmaintained...)

**Comment by nikomatsakis** [comment]
@cuviper I'm happy to close this PR for now, though it may well be that the perf hit of crossbeam is worth it in exchange for having memory recovery (that is, I'm not quite sure what the deque crate does about memory reclamation, but I imagine it has a sort of leak -- i.e., the memory usage is proportional to the maximum length of the queue and never goes back down). But it'd be interesting to know if the crossbeam deque can indeed be optimized. I don't know that anyone has ever tried to analyze its performance.

**Comment by nikomatsakis** [comment]
I've pinged @aturon but he's a busy guy =)

**Comment by nikomatsakis** [comment]
It occurs to me that we've been remiss in not pinging the authors of the deque crate as well. =) @Amanieu @kinghajj @faern -- perhaps one of you can elaborate a bit on what the deque crater and crossbeam differ architecturally? I'm pretty happy to stick with deque -- particularly since it seems to perform [better overall](https://github.com/nikomatsakis/rayon/pull/195#issuecomment-269981735) -- but I'd like to know the origin of those differences.

**Comment by nikomatsakis** [comment]
I guess that [this comment by @rphmeier](https://github.com/nikomatsakis/rayon/issues/33#issuecomment-177190822) is probably "the answer":

> The strategy which the deque crate uses is to store old buffers in a linked list, doubling in size whenever growth is needed. This ends up converging at 2N space usage for N elements, so it's not an unbounded memory leak. You could alternatively adopt a strategy (requiring modification of the deque crate) to free the extra buffers when the deque provably has no jobs available. A pop operation returning "None" might even be enough proof.

Anyway, this is clearly an impl detail that we can tweak as needed. Seems like we should stick with deque for now; perhaps in the future we will trade if memory usage becomes a serious obstacle (or else we could make it tunable). The benchmarks suggest that crossbeam's more flexible memory management story does come at a price, though. It's interesting that `nbody-parreduce` is so dramatically effected: I consider that to be more than a microbenchmark.

**Comment by kinghajj** [comment]
Ha, I'm humbled that you consider me an "author" of this data structure, when all I really did was salvage it from a pre-1.0 version of `std`! If the `git blame` is correct, @alexchrichton was the original author. I was under the impression, though, that @aturon had already incorporated this structure into `crossbeam`, and improved it using his generational collection mechanism? (I've been out-of-the-loop, perhaps it's been removed?)

**Comment by cuviper** [comment]
@kinghajj I think that's basically the chase-lev stuff I'm using in this PR.  But it appears that the generational improvements are actually a hindrance here, at least in micro-benchmarks that hammer hard on it.

@nikomatsakis Have you seen the growth of the deque be a problem in practice?  Or is this more of a theoretical concern?  If we want deque to sometimes free extra buffers, perhaps we could do that when a thread goes to sleep (having no work to do, and nothing to steal).

**Comment by Amanieu** [comment]
I doubt deque growth is a problem in practice since you would never have more than `log2(N)` jobs in deque for a parallel iterator of `N` elements. This means that in most cases you'll run out of address space before you ever have 64 jobs in the deque (on a 64-bit machine).

**Comment by nikomatsakis** [comment]
@cuviper 

> Or is this more of a theoretical concern?

At present, it's a theoretical concern.

**Comment by nikomatsakis** [comment]
OK, I'm going to close this PR for now. We can always revisit, not hard to do. =)

**Comment by stjepang** [comment]
I'd like to point out that crossbeam's Chase-Lev deque has multiple flaws relevant to this discussion:

1. The destructor doesn't eagerly free the current underlying buffer. With respect to memory reclamation, this is even *worse* than the `deque` crate. But this is an easy problem to fix nonetheless.
2. Deque's worker pins threads even though it doesn't have to. This is due to a missing piece in the API.
3. Memory is very lazily reclaimed. Garbage first gets buffered in a vector that starts freeing garbage only after it collects at least 32 objects. This means that your deque has to grow/shrink 32 times before any garbage starts being collected! This a very difficult problem to fix gracefully and, honestly, I believe crossbeam's whole epoch system needs a big revamp.
4. Pinning is very costly and performs multiple atomic operations. This harms performance quite a bit.

Issues 1 and 2 can be pretty easily fixed. However, issues 3 and 4 will require a lot of thinking.

For that reason, I decided to build a new epoch-based system from scratch that doesn't suffer from any of those problems. Memory is eagerly collected (incrementally, too!) and it's deque performance is on par with the `deque` crate. By the way, it builds important groundwork for several new lock-free data structures. Stay tuned. :)

Here are the benchmark numbers (rayon with `deque` vs with `coco`):
```
name                                                     out_default ns/iter  out_coco ns/iter  diff ns/iter   diff % 
factorial::factorial_iterator                            21,390,026           21,177,275            -212,751   -0.99% 
factorial::factorial_join                                9,877,750            10,086,878             209,128    2.12% 
factorial::factorial_par_iter                            10,217,860           10,112,900            -104,960   -1.03% 
factorial::factorial_recursion                           11,780,777           11,552,929            -227,848   -1.93% 
fibonacci::fibonacci_iterative                           6                    6                            0    0.00% 
fibonacci::fibonacci_join_1_2                            75,528,632           49,260,317         -26,268,315  -34.78% 
fibonacci::fibonacci_join_2_1                            77,306,493           71,231,571          -6,074,922   -7.86% 
fibonacci::fibonacci_recursive                           13,644,783           13,864,686             219,903    1.61% 
find::size1::parallel_find_common                        6,411                6,630                      219    3.42% 
find::size1::parallel_find_first                         4,360                4,367                        7    0.16% 
find::size1::parallel_find_last                          4,913,700            4,978,611               64,911    1.32% 
find::size1::parallel_find_middle                        3,291,058            3,275,991              -15,067   -0.46% 
find::size1::parallel_find_missing                       5,150,065            5,253,989              103,924    2.02% 
find::size1::serial_find_common                          3,409                3,392                      -17   -0.50% 
find::size1::serial_find_first                           1                    1                            0    0.00% 
find::size1::serial_find_last                            3,831,330            3,934,411              103,081    2.69% 
find::size1::serial_find_middle                          2,553,543            2,625,493               71,950    2.82% 
find::size1::serial_find_missing                         3,788,467            3,788,592                  125    0.00% 
join_microbench::increment_all                           38,135               37,117                  -1,018   -2.67% 
join_microbench::join_recursively                        1,430,528            1,232,055             -198,473  -13.87% 
map_collect::i_mod_10_to_i::with_collect                 7,442,920            7,380,971              -61,949   -0.83% 
map_collect::i_mod_10_to_i::with_fold                    3,258,444            3,335,571               77,127    2.37% 
map_collect::i_mod_10_to_i::with_fold_vec                3,200,652            3,406,099              205,447    6.42% 
map_collect::i_mod_10_to_i::with_linked_list             16,796,306           16,943,789             147,483    0.88% 
map_collect::i_mod_10_to_i::with_linked_list_vec         5,784,242            5,790,471                6,229    0.11% 
map_collect::i_mod_10_to_i::with_linked_list_vec_sized   7,444,058            7,431,988              -12,070   -0.16% 
map_collect::i_mod_10_to_i::with_mutex                   60,885,295           66,477,665           5,592,370    9.19% 
map_collect::i_mod_10_to_i::with_mutex_vec               7,259,321            7,308,820               49,499    0.68% 
map_collect::i_to_i::with_collect                        23,383,573           24,583,124           1,199,551    5.13% 
map_collect::i_to_i::with_fold                           76,238,609           76,544,997             306,388    0.40% 
map_collect::i_to_i::with_fold_vec                       75,386,300           73,658,552          -1,727,748   -2.29% 
map_collect::i_to_i::with_linked_list                    35,335,042           34,011,009          -1,324,033   -3.75% 
map_collect::i_to_i::with_linked_list_vec                35,549,043           35,363,242            -185,801   -0.52% 
map_collect::i_to_i::with_linked_list_vec_sized          23,162,079           24,564,018           1,401,939    6.05% 
map_collect::i_to_i::with_mutex                          110,094,454          109,187,469           -906,985   -0.82% 
map_collect::i_to_i::with_mutex_vec                      41,173,420           40,810,709            -362,711   -0.88% 
matmul::bench::bench_matmul_strassen                     8,512,046            7,970,515             -541,531   -6.36% 
mergesort::bench::merge_sort_par_bench                   10,443,915           9,868,967             -574,948   -5.51% 
mergesort::bench::merge_sort_seq_bench                   28,179,968           28,596,133             416,165    1.48% 
nbody::bench::nbody_par                                  14,363,148           13,029,686          -1,333,462   -9.28% 
nbody::bench::nbody_parreduce                            21,953,491           21,432,613            -520,878   -2.37% 
nbody::bench::nbody_seq                                  27,580,869           26,967,340            -613,529   -2.22% 
pythagoras::euclid_faux_serial                           31,278,384           30,585,341            -693,043   -2.22% 
pythagoras::euclid_parallel_full                         93,319,870           76,696,200         -16,623,670  -17.81% 
pythagoras::euclid_parallel_one                          31,269,494           30,513,474            -756,020   -2.42% 
pythagoras::euclid_parallel_outer                        11,124,106           11,089,224             -34,882   -0.31% 
pythagoras::euclid_parallel_weightless                   12,228,238           11,408,135            -820,103   -6.71% 
pythagoras::euclid_serial                                30,448,597           29,914,544            -534,053   -1.75% 
quicksort::bench::quick_sort_par_bench                   17,014,693           17,067,941              53,248    0.31% 
quicksort::bench::quick_sort_seq_bench                   41,256,870           41,065,894            -190,976   -0.46% 
sieve::bench::sieve_chunks                               10,574,265           10,831,257             256,992    2.43% 
sieve::bench::sieve_parallel                             6,705,675            6,786,495               80,820    1.21% 
sieve::bench::sieve_serial                               25,445,601           26,237,118             791,517    3.11% 
tsp::bench::dj10                                         14,089,549           14,130,103              40,554    0.29% 
vec_collect::vec_i::with_collect                         5,077,521            5,310,757              233,236    4.59% 
vec_collect::vec_i::with_collect_into                    5,265,696            5,195,431              -70,265   -1.33% 
vec_collect::vec_i::with_collect_into_reused             2,912,681            2,853,764              -58,917   -2.02% 
vec_collect::vec_i::with_fold                            31,525,347           33,294,918           1,769,571    5.61% 
vec_collect::vec_i::with_linked_list_vec                 18,105,117           18,347,274             242,157    1.34% 
vec_collect::vec_i::with_linked_list_vec_sized           14,013,742           13,888,846            -124,896   -0.89% 
vec_collect::vec_i_filtered::with_collect                14,197,194           14,400,380             203,186    1.43% 
vec_collect::vec_i_filtered::with_fold                   32,886,372           33,260,847             374,475    1.14% 
vec_collect::vec_i_filtered::with_linked_list_vec        18,253,419           18,649,635             396,216    2.17% 
vec_collect::vec_i_filtered::with_linked_list_vec_sized  13,812,981           14,461,579             648,598    4.70% 
```

The implementation is available here: https://github.com/stjepang/coco
Now I'd like write thorough unit tests and sanitization tests, then release version 0.1 over the next week.

**Comment by cuviper** [comment]
@stjepang Now *that* looks very promising!  Some good wins across the board, and the cases that regressed appear to be allocator/mutex heavy -- probably highly variable to begin with.  I look forward to seeing this!

**Pull request closed without merging**
