### PR TITLE
Introduce prelude

### LINKED ISSUE #59: Using `par_iter::*` is too broad
The docs recommend `use rayon::par_iter::*;` -- but this includes every `pub mod`, and those have very generic names.  So something simple like this fails:

```rust
use rayon::par_iter::*;
use std::slice;
```

```error: a module named `slice` has already been imported in this module```

If those submodules really need to be public, perhaps there should be a prelude to glob use instead?

### PR DESCRIPTION
**Pull request by nikomatsakis**
Fixes #59.

cc @cuviper

### CODE REVIEW

**Comment by nikomatsakis** [comment]
But I wonder if we should include an alias for rayon itself, so that one can call `rayon::join` without having to do:

```
use rayon;
use rayon::prelude::*;
```

which is annoying.

**Comment by nikomatsakis** [comment]
Could do something hacky like

```
pub mod rayon {
    pub use super::super::*;
}
```

to re-export everything from the top-level in the prelude :)

**Comment by nikomatsakis** [comment]
But I guess that would make simple programs like

```rust
extern crate rayon;
use rayon::prelude::*;
```

fail to compile, so I think I will not do it for now.

**Comment by cuviper** [comment]
Did you forget to add your `prelude.rs`?

**Comment by nikomatsakis** [comment]
@cuviper yes :)

**Comment by cuviper** [comment]
:+1:

**Comment by reem** [comment]
Personally I just use `::rayon` for accessing the top-level functions except in the crate root where it's just `rayon`. I don't think it's a big deal to ask people to `use rayon;` if they really don't want to have the leading `::`.

**Pull request merged**
