### PR TITLE
Add more map_collect benchmark alternatives

### PR DESCRIPTION
**Pull request by cuviper**

### CODE REVIEW

**Comment by cuviper** [comment]
h/t @edre for figuring out that `linked_list_vec` need a size hint.  I think that's now the most promising approach to use for generalized collection.  My results:

```
test map_collect::i_mod_10_to_i::with_collect               ... bench:  18,112,898 ns/iter (+/- 7,910,388)
test map_collect::i_mod_10_to_i::with_fold                  ... bench:   1,756,912 ns/iter (+/- 1,535,430)
test map_collect::i_mod_10_to_i::with_fold_vec              ... bench:   1,847,589 ns/iter (+/- 2,056,629)
test map_collect::i_mod_10_to_i::with_linked_list           ... bench:  18,429,389 ns/iter (+/- 9,043,025)
test map_collect::i_mod_10_to_i::with_linked_list_vec       ... bench:   9,678,659 ns/iter (+/- 5,891,813)
test map_collect::i_mod_10_to_i::with_linked_list_vec_sized ... bench:  10,362,794 ns/iter (+/- 8,448,371)
test map_collect::i_mod_10_to_i::with_mutex                 ... bench:  60,025,030 ns/iter (+/- 998,976)
test map_collect::i_mod_10_to_i::with_mutex_vec             ... bench:   6,141,926 ns/iter (+/- 1,293,354)
test map_collect::i_to_i::with_collect                      ... bench:  32,767,563 ns/iter (+/- 14,504,955)
test map_collect::i_to_i::with_fold                         ... bench:  90,121,341 ns/iter (+/- 8,154,321)
test map_collect::i_to_i::with_fold_vec                     ... bench:  87,075,617 ns/iter (+/- 6,615,325)
test map_collect::i_to_i::with_linked_list                  ... bench:  31,259,271 ns/iter (+/- 12,613,807)
test map_collect::i_to_i::with_linked_list_vec              ... bench:  44,591,673 ns/iter (+/- 21,154,818)
test map_collect::i_to_i::with_linked_list_vec_sized        ... bench:  21,340,589 ns/iter (+/- 8,752,931)
test map_collect::i_to_i::with_mutex                        ... bench: 104,561,035 ns/iter (+/- 1,946,771)
test map_collect::i_to_i::with_mutex_vec                    ... bench:  62,132,853 ns/iter (+/- 13,183,860)
```

**Comment by nikomatsakis** [comment]
Can you measure time to build a vector using the current, precise collect vs a linked list of vectors? Just curious 
On Nov 6, 2016 14:00, Josh Stone <notifications@github.com> wrote:h/t @edre for figuring out that linked_list_vec need a size hint.  I think that's now the most promising approach to use for generalized collection.  My results:

test map_collect::i_mod_10_to_i::with_collect               ... bench:  18,112,898 ns/iter (+/- 7,910,388)
test map_collect::i_mod_10_to_i::with_fold                  ... bench:   1,756,912 ns/iter (+/- 1,535,430)
test map_collect::i_mod_10_to_i::with_fold_vec              ... bench:   1,847,589 ns/iter (+/- 2,056,629)
test map_collect::i_mod_10_to_i::with_linked_list           ... bench:  18,429,389 ns/iter (+/- 9,043,025)
test map_collect::i_mod_10_to_i::with_linked_list_vec       ... bench:   9,678,659 ns/iter (+/- 5,891,813)
test map_collect::i_mod_10_to_i::with_linked_list_vec_sized ... bench:  10,362,794 ns/iter (+/- 8,448,371)
test map_collect::i_mod_10_to_i::with_mutex                 ... bench:  60,025,030 ns/iter (+/- 998,976)
test map_collect::i_mod_10_to_i::with_mutex_vec             ... bench:   6,141,926 ns/iter (+/- 1,293,354)
test map_collect::i_to_i::with_collect                      ... bench:  32,767,563 ns/iter (+/- 14,504,955)
test map_collect::i_to_i::with_fold                         ... bench:  90,121,341 ns/iter (+/- 8,154,321)
test map_collect::i_to_i::with_fold_vec                     ... bench:  87,075,617 ns/iter (+/- 6,615,325)
test map_collect::i_to_i::with_linked_list                  ... bench:  31,259,271 ns/iter (+/- 12,613,807)
test map_collect::i_to_i::with_linked_list_vec              ... bench:  44,591,673 ns/iter (+/- 21,154,818)
test map_collect::i_to_i::with_linked_list_vec_sized        ... bench:  21,340,589 ns/iter (+/- 8,752,931)
test map_collect::i_to_i::with_mutex                        ... bench: 104,561,035 ns/iter (+/- 1,946,771)
test map_collect::i_to_i::with_mutex_vec                    ... bench:  62,132,853 ns/iter (+/- 13,183,860)

**Comment by cuviper** [comment]
Crudely hacking vectors into the current benchmark, I get:

```
test map_collect::i_to_i::vec_exact                         ... bench:     647,942 ns/iter (+/- 1,152,700)
test map_collect::i_to_i::vec_linked                        ... bench:  13,133,551 ns/iter (+/- 6,723,150)
test map_collect::i_to_i::vec_linked_vec                    ... bench:   4,377,981 ns/iter (+/- 4,026,273)
test map_collect::i_to_i::vec_linked_vec_sized              ... bench:   2,775,064 ns/iter (+/- 4,022,221)
```

So, we *really* want to use exact collection when possible.  Where's that stable specialization? ...

**Comment by nikomatsakis** [comment]
@cuviper thanks =)

**Comment by cuviper** [comment]
I think you hit "merge" *after* you had already merged #124, so this didn't actually make it to master.

Should I open a new PR, and perhaps actually convert `collect` to the `with_linked_list_vec_sized` style?

**Comment by nikomatsakis** [comment]
oh, I didn't realize this was targeting my branch. :) I wondered why it didn't conflict, just thought GH was being smart somehow. Feel free to open a PR against master, sorry, and changing the default strategy makes sense too!

**Pull request merged**
