### PR TITLE
Add zip_eq adapter to IndexedParallelIterator (ZipEq struct version)

### LINKED ISSUE #386: implement `zip_longest` and `zip_eq`
The `itertools` crate offers [a `zip_longest` method](https://docs.rs/itertools/0.6.0/itertools/trait.Itertools.html#method.zip_longest) and a `zip_eq`. These are variants on zip. `zip_eq` basically just asserts that the lengths of the two iterators are equal -- with parallel iterators, since we only zip things for which the lengths are known, we can trivially check this. `zip_longest` is a bit more complex. 

The implementation of `zip_longest` looks very much like [the existing `zip` iterator][z], I expect, except that -- [when we fall back to sequential execution](https://github.com/nikomatsakis/rayon/blob/29ab2edf82b68b7dcd6370ee296e741d487ba9bd/src/iter/zip.rs#L118) -- we can use the itertools `zip_longest` function instead of `zip`.

[z]: https://github.com/nikomatsakis/rayon/blob/29ab2edf82b68b7dcd6370ee296e741d487ba9bd/src/iter/zip.rs#L7-L10

### PR DESCRIPTION
**Pull request by chrisvittal**
This replaces #389, and is much the same. Re-implemented `zip_eq` using a `ZipEq` struct that is a wrapper around `Zip` to better align `zip_eq` with the adapters present in `rayon`, `itertools`, and the standard library.

Closes #386, as I believe it has been decided to not implement `zip_longest`.

@cuviper it was unclear from your comments where you wanted additional documentation. Please advise and I will update.

### CODE REVIEW

**Comment by cuviper** [comment]
> it was unclear from your comments where you wanted additional documentation.

On `struct ZipEq`, since this is public.  Doesn't need to be a lot, just something relating it back to the `zip_eq` method.

**Comment by chrisvittal** [comment]
I've been attempting to diagnose CI failures on nightly, and it appears that `compiletest_rs` is broken on current nightly (rustc 1.20.0-nightly (3bfc18a96 2017-06-29)) on mac and linux. I will investigate more when I get the chance.

The nightly before today works fine.

**Comment by cuviper** [comment]
It seems compiletest_rs 0.2.8 fixed that issue.  I restarted your nightly CI runs, and Linux passed, but macOS is still queued...

**Comment by chrisvittal** [comment]
In the demo, there are dependencies on both cocoa-0.3.3 and cocoa-0.5.2, which both fail to build on current nightly. It seems that servo/cocoa-rs#166 fixed this for the current cocoa (0.9.2), but I'm not sure what we can do here.

**Comment by cuviper** [comment]
Well that's awkward.  I wonder what caused the change in `Sized` behavior -- @nikomatsakis ?

Our dependency tree looks something like this:

- rayon-demo
  - glium
    - glutin
      - cocoa 0.3
      - winit
        - cocoa 0.5

Perhaps we should just skip rayon-demo for CI on macOS.  We'll still have the basic rayon tests, but we don't need to get in the business of troubleshooting graphics stacks here...

**Comment by bluss** [comment]
I think that this is better than `zip_eq` in itertools, because this is checking up front and then iterating unhindered.

itertools' zip_eq is lazy (only can panic if it reaches an end) and consequently gets in the way of good loop optimizations since it's putting a panic check between each iterator element.

If itertools changes it might be to change `zip_eq` to apply in just the cases where we can check iterator length up front (a passing thought, it might then exclude exactly those cases, like when filtering, where the check is most crucial.. hmm).

**Comment by cuviper** [comment]
Can you please rebase this to see how CI fares now?

**Comment by cuviper** [comment]
Thanks!

**Pull request merged**
