### PR TITLE
[WIP] Collect based on vec tree

### PR DESCRIPTION
**Pull request by nikomatsakis**
Just for fun, this is a variant on #124 that uses a `VecTree` (a lame-o data structure I just whipped up) as its intermediate storage. It also builds on #120. =) This allows us to build maps from non-exact parallel iterators.

Definitely need to make some benchmarks to test the performance of this as compared to a vector. Specialization would probably let us have the best of both worlds here once that stabilizes.

And then I'd like to implement flat-combining and compare the performance of both to that. =)

### CODE REVIEW

**Comment by edre** [comment]
While I think a LinkedList<Vec<T>> is sufficient for this use case, this VecTree could be used as both an efficient producer and an efficient consumer. I don't think there's anything currently in the API that could benefit from this though.

**Comment by nikomatsakis** [comment]
Here are the advantages I see:

- Using a vector at the leaves may be more efficient, if the leaves are sufficiently large
    - this will depend on the efficacy of `fold` in creating good groupings though
- As @edre said, given a vec-tree, it's easy to produce again
    - one possible use would be to allow creating a `Vec` from a non-exact par iter
    - basically build into a vec-tree and then store back out

The last point is one of the reasons I've been wanting to experiment with `VecTree`. I was somewhat inspired by papers like [Lazy Tree Splitting](http://manticore.cs.uchicago.edu/papers/jfp-lts-submitted.pdf) and [Data Only Flattening](http://manticore.cs.uchicago.edu/papers/ppopp13-flat.pdf) that discuss the use of trees of this kind. 

That said, it'd be worth trying and comparing against a linked list. It's true that they are a good fit too.

**Comment by cuviper** [comment]
I'm suggesting to use vectors in the linked list nodes, so you'd still get your grouping.

I see how using a tree makes it possible to fork again, e.g. as a new `into_par_iter`, but I'm not clear if that's actually what you're saying.

**Comment by nikomatsakis** [comment]
Ah, I hadn't considered a `LinkedList<Vec>`. But yes I was saying that using a tree lets us do a new `into_par_iter`. In any case, upon further consideration I decided to update the original PR to support a `LinkedList` -- I'd like to experiment with stuff like `VecTree`, but I'd prefer to land `collect()` ASAP, and supporting a data structure like `LinkedList` makes sense anyhow.

**Comment by nikomatsakis** [comment]
Closing this for now. Interesting thought experiment.

**Pull request closed without merging**
