### PR TITLE
Tweaks to the limit number of threads PR

### PR DESCRIPTION
**Pull request by nikomatsakis**
This is a tweaked version of PR #29 with some additional commits.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
D'oh, I have to fix the demos.

**Comment by willi-kappler** [comment]
It's just these three things: `InitResult`, `NumberOfThreadsZero`, `NumberOfThreadsNotEqual`. Besides that it looks really good! Thanks for "mentoring" and letting me work on this ;-)

**Comment by lilianmoraru** [comment]
Note the panic message "expected InitOk" - but there is no more InitOk in the enum(that was InitResult and now InitError).

**Comment by nikomatsakis** [comment]
it occurred to me that the error type should really implement [the Error trait](http://doc.rust-lang.org/std/error/index.html#the-error-trait)

**Comment by nikomatsakis** [comment]
But I'll leave that for another PR. :)

**Pull request merged**
