### PR TITLE
IntoParallelIterator for Option and Result

### LINKED ISSUE #80: `par_iter` for `Option`
It would be nice to have one to allow uses like:

```rust
paths
    .map(File::open)
    .flat_map(Result::ok)
    // ...
```

### PR DESCRIPTION
**Pull request by cuviper**
Fixes #80.

### CODE REVIEW

**Comment by cuviper** [comment]
I'm not sure this is terribly useful, but I said in #80 that it would be easy, so here it is. :)

**Comment by nikomatsakis** [comment]
Looks good -- seems like this would work best if we had `chain` attached to it.

**Comment by nikomatsakis** [comment]
By "work best" I mean "be most useful". I often want to do something like "iterate over this slice and maybe one more thing".

**Comment by cuviper** [comment]
Huh, there's no `ParallelIterator::chain` yet, but that definitely sounds like a good idea, and I agree it would compose nicely here.

**Pull request merged**
